namespace EscapeFromIsleMainak.Components
{
    public enum Id
    {
        /* Scenes */
        SCENE_BUNGALOW_ROOM,
        SCENE_BUNGALOW_BATHROOM,
        SCENE_BUNGALOW_BALCONY,
        SCENE_INBETWEEN_BUNGALOWS,
        SCENE_NEIGHBOUR_BUNGALOW_BALCONY,
        SCENE_SPECIAL_VEHICLE_BOAT,
        SCENE_SPECIAL_VEHICLE_BOAT_DRIVING,
        SCENE_SPECIAL_VEHICLE_JEEP,
        SCENE_SPECIAL_VEHICLE_JEEP_DRIVING,
        SCENE_NEIGHBOUR_BUNGALOW_ROOM,
        SCENE_NEIGHBOUR_BUNGALOW_BATHROOM,
        SCENE_GAS_STATION,
        SCENE_VILLAGE_PROMENADE,
        SCENE_VILLAGE_BEACH,
        SCENE_HARBOR_ENTRANCE,
        SCENE_HARBOR_JETTY,
        SCENE_TEST,
        /* Items */
        ITEM_NOTE,
        ITEM_BROKEN_BOTTLE,
        ITEM_PASSED_OUT_RAT,
        ITEM_BOAT_KEY,
        ITEM_JEEP_KEY,
        /* Actions */
        ACTION_READ,
        ACTION_USE,
        /* Entities */
        ENTITY_BUNGALOW_RAT,
        ENTITY_BUNGALOW_SHADOWY_ZOMBIE
    }

}