scene.title EXT. BETWEEN BUNGALOWS - NIGHT
scene.scriptBegin
You're standing between your bungalow and the the neighbouring bungalow. The vehicle you and your friend rented is gone but the neighbour's JEEP is still parked.

Usually there's a small garden or a pool in front of bungalows but there's only a couple of bushes and some flat stones sporadically placed here and there to mark a crude path between the homes. You're truly on an untouched paradise island.

You can GO back HOME to your bungalow or walk to up the stairs to your neighbour's BUNGALOW where the shadowy figure is.
scene.scriptEnd